
spring:

  application:
    name: web-rest-test

  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  datasource:
    url: jdbc:postgresql://web-rest-test-db:5432/web-rest-test-database?currentSchema=public
    username: web-rest-test-user
    password: web-rest-test-password
